### ISSUE TITLE
UE4.26 android编译不过

### ISSUE THREAD

**Issue by mingxxming** [fairygui/FairyGUI-unreal#2]
In file included from C:/Projects/evh/Intermediate/Build/Android/evh/Development/FairyGUI/Module.FairyGUI.cpp:41:
UATHelper: Packaging (Android (ETC2)):     C:/Projects/evh/Plugins/FairyGUI-unreal/Source/FairyGUI/Private/UI/GObject.cpp(638,9): warning: UProperty has been renamed to FProperty Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-W#pragma-messages]
UATHelper: Packaging (Android (ETC2)):             UProperty* Property = GetClass()->FindPropertyByName(FName(*FString("On").Append(EventType.ToString())));
UATHelper: Packaging (Android (ETC2)):             ^
UATHelper: Packaging (Android (ETC2)):     C:/Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\CoreUObject\Public\UObject\DefineUPropertyMacros.h(8,20): note: expanded from macro 'UProperty'
UATHelper: Packaging (Android (ETC2)):             #define UProperty DEPRECATED_MACRO(4.25, "UProperty has been renamed to FProperty") FProperty
UATHelper: Packaging (Android (ETC2)):                               ^
UATHelper: Packaging (Android (ETC2)):     C:/Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformCompilerPreSetup.h(88,45): note: expanded from macro 'DEPRECATED_MACRO'
UATHelper: Packaging (Android (ETC2)):             #define DEPRECATED_MACRO(Version, Message) EMIT_CUSTOM_WARNING(Message " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")
UATHelper: Packaging (Android (ETC2)):                                                        ^
UATHelper: Packaging (Android (ETC2)):     C:/Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\GenericPlatform\GenericPlatformCompilerPreSetup.h(84,3): note: expanded from macro 'EMIT_CUSTOM_WARNING'
UATHelper: Packaging (Android (ETC2)):                     EMIT_CUSTOM_WARNING_AT_LINE(__LINE__, Warning)
UATHelper: Packaging (Android (ETC2)):                     ^
UATHelper: Packaging (Android (ETC2)):     C:/Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Core\Public\Clang\ClangPlatformCompilerPreSetup.h(172,3): note: expanded from macro 'EMIT_CUSTOM_WARNING_AT_LINE'
UATHelper: Packaging (Android (ETC2)):                     _Pragma(PREPROCESSOR_TO_STRING(message(Warning)))
UATHelper: Packaging (Android (ETC2)):                     ^
UATHelper: Packaging (Android (ETC2)):     <scratch space>(7,2): note: expanded from here
UATHelper: Packaging (Android (ETC2)):      message("UProperty has been renamed to FProperty" " Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.")
UATHelper: Packaging (Android (ETC2)):      ^
UATHelper: Packaging (Android (ETC2)):     In file included from C:/Projects/evh/Intermediate/Build/Android/evh/Development/FairyGUI/Module.FairyGUI.cpp:62:
UATHelper: Packaging (Android (ETC2)):     C:/Projects/evh/Plugins/FairyGUI-unreal/Source/FairyGUI/Private/UIPackageAsset.cpp(4,23): error: out-of-line definition of 'GetAssetRegistryTags' does not match any declaration in 'UUIPackageAsset'
UATHelper: Packaging (Android (ETC2)):     void UUIPackageAsset::GetAssetRegistryTags(TArray<FAssetRegistryTag>& OutTags) const
UATHelper: Packaging (Android (ETC2)):                           ^~~~~~~~~~~~~~~~~~~~
UATHelper: Packaging (Android (ETC2)):     In file included from C:/Projects/evh/Intermediate/Build/Android/evh/Development/FairyGUI/Module.FairyGUI.cpp:83:
UATHelper: Packaging (Android (ETC2)):     C:/Projects/evh/Plugins/FairyGUI-unreal/Source/FairyGUI/Private/Widgets/NTexture.cpp(15,24): error: no member named 'CompressionNone' in 'UTexture2D'; did you mean 'CompressionYCoCg'?
UATHelper: Packaging (Android (ETC2)):             NativeTexture->CompressionNone = true;
UATHelper: Packaging (Android (ETC2)):                            ^~~~~~~~~~~~~~~
UATHelper: Packaging (Android (ETC2)):                            CompressionYCoCg
UATHelper: Packaging (Android (ETC2)):     C:/Program Files\Epic Games\UE_4.26\Engine\Source\Runtime\Engine\Classes\Engine\Texture.h(839,8): note: 'CompressionYCoCg' declared here
UATHelper: Packaging (Android (ETC2)):             uint8 CompressionYCoCg : 1;
UATHelper: Packaging (Android (ETC2)):                   ^
UATHelper: Packaging (Android (ETC2)):     In file included from C:/Projects/evh/Intermediate/Build/Android/evh/Development/FairyGUI/Module.FairyGUI.cpp:83:
UATHelper: Packaging (Android (ETC2)):     C:/Projects/evh/Plugins/FairyGUI-unreal/Source/FairyGUI/Private/Widgets/NTexture.cpp(16,24): error: no member named 'MipGenSettings' in 'UTexture2D'
UATHelper: Packaging (Android (ETC2)):             NativeTexture->MipGenSettings = TMGS_NoMipmaps;
UATHelper: Packaging (Android (ETC2)):             ~~~~~~~~~~~~~  ^
UATHelper: Packaging (Android (ETC2)):     1 warning and 3 errors generated.
PackagingResults: Warning: UProperty has been renamed to FProperty Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-W#pragma-messages]
PackagingResults: Error: out-of-line definition of 'GetAssetRegistryTags' does not match any declaration in 'UUIPackageAsset'
PackagingResults: Error: no member named 'CompressionNone' in 'UTexture2D'; did you mean 'CompressionYCoCg'?
PackagingResults: Error: no member named 'MipGenSettings' in 'UTexture2D'

**Comment by huzhangyang** [comment]
https://github.com/xiongyouliang/FairyGUI-unreal/commit/4a37a359f9b3c9a4166a81fb7623cdf8630195ca
